name 'Giuseppe Misurelli'
maintainer 'Giuseppe Misurelli'
maintainer_email 'bejohnzorn@gmail.com'
license ''
description 'Installs/Configures chef-postgresql-server'
long_description 'Installs/Configures chef-postgresql-server'
version '0.1.0'
